---
abstract: 'a Perl Exceptions module where exceptions are not objects but simple strings.'
author:
  - 'Damien Krotkine <dams@cpan.org>'
build_requires:
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Test::Fatal: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.63_03
  Module::Build::Tiny: 0.030
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.005, CPAN::Meta::Converter version 2.132830'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Exception-Stringy
requires:
  perl: 5.013002
resources:
  bugtracker: https://github.com/dams/p5-exception-stringy/issues
  homepage: https://github.com/dams/p5-exception-stringy
  repository: https://github.com/dams/p5-exception-stringy.git
version: 0.11
